# Generated by Django 3.0 on 2021-05-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_bank', models.CharField(choices=[('Supratech Blood Bank,Thaltej', 'Supratech Blood Bank,Thaltej'), ('Indian Blood Service , Ellisbridge', 'Indian Blood Service , Ellisbridge')], max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('blood_price', models.IntegerField()),
                ('blood_quantity', models.IntegerField()),
                ('blood_description', models.TextField()),
                ('blood_image', models.ImageField(upload_to='blood_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
